services:
  keep-frontend-common:
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_SECRET=f08773dcfbb51517f108e752fb133c33cbf3166fba89d7251ae8e4ed561e2287
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_OTEL_COLLECTOR_URL=http://localhost:4318


  keep-backend-common:
    environment:
      - PORT=8080
      - SECRET_MANAGER_TYPE=FILE
      - SECRET_MANAGER_DIRECTORY=/state
      - DATABASE_CONNECTION_STRING=sqlite:////state/db.sqlite3?check_same_thread=False
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - USE_NGROK=false
