global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "keep"
    static_configs:
      - targets: ["host.docker.internal:8080"]
    metrics_path: "/metrics"
    http_headers:
      x-api-key:
        values:
          - "keep-api-key"
