name: Test Microservices Build

on:
  pull_request:
    branches:
      - development

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    if: github.head_ref == 'seperate-worker-logic'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Frontend
        uses: docker/build-push-action@v4
        with:
          context: keep-ui
          file: ./docker/Dockerfile.ui
          push: false
          tags: keep-frontend:test

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    if: github.head_ref == 'seperate-worker-logic'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.api
          push: false
          tags: keep-backend:test

  build-event-handler:
    name: Build Event Handler
    runs-on: ubuntu-latest
    if: github.head_ref == 'seperate-worker-logic'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Event Handler
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.event_handler
          push: false
          tags: keep-event-handler:test
